parameters:
    email_templates:
        # Provider email templates having a particular keyword in the subject
        -
            id: !php/const App\Enum\EmailTemplate::OUESTFRANCE_IMMO_NEUF
            provider: !php/const App\Enum\Provider::OUESTFRANCE_IMMO
            name: "\"Ouestfrance-immo.com\""
            email: alerte@news.ouestfrance-immo.com
            subject_keyword: neuf
        -
            id: !php/const App\Enum\EmailTemplate::SELOGER_2
            provider: !php/const App\Enum\Provider::SELOGER
            name: SeLoger
            email: seloger@al.alerteimmo.com
            subject_keyword: exclusivités

        # Provider email templates without a particular subject
        -
            id: !php/const App\Enum\EmailTemplate::BIENICI
            provider: !php/const App\Enum\Provider::BIENICI
            name: "\"Bien'ici\""
            email: no_reply@bienici.com
        -
            id: !php/const App\Enum\EmailTemplate::FNAIM
            provider: !php/const App\Enum\Provider::FNAIM
            name: FNAIM
            email: no-reply@fnaim.fr
        -
            id: !php/const App\Enum\EmailTemplate::LEBONCOIN
            provider: !php/const App\Enum\Provider::LEBONCOIN
            name: leboncoin
            email: no.reply@leboncoin.fr
        -
            id: !php/const App\Enum\EmailTemplate::LOGIC_IMMO
            provider: !php/const App\Enum\Provider::LOGIC_IMMO
            name: "\"Logic-immo.com\""
            email: news@logicimmo.nmp1.com
        -
            id: !php/const App\Enum\EmailTemplate::LOGIC_IMMO_2
            provider: !php/const App\Enum\Provider::LOGIC_IMMO
            name: "\"Logic-Immo.com\""
            email: news@logicimmo.nmp1.com
        -
            id: !php/const App\Enum\EmailTemplate::LOGIC_IMMO_NEUF
            provider: !php/const App\Enum\Provider::LOGIC_IMMO
            name: "\"Logic-ImmoNeuf.com\""
            email: news@logicimmo.nmp1.com
        -
            id: !php/const App\Enum\EmailTemplate::OUESTFRANCE_IMMO
            provider: !php/const App\Enum\Provider::OUESTFRANCE_IMMO
            name: "\"Ouestfrance-immo.com\""
            email: alerte@news.ouestfrance-immo.com
        -
            id: !php/const App\Enum\EmailTemplate::OUESTFRANCE_IMMO_NEUF_2
            provider: !php/const App\Enum\Provider::OUESTFRANCE_IMMO
            name: "\"Ouestfrance-immo.com\""
            email: contact_alerte@news.ouestfrance-immo.com
        -
            id: !php/const App\Enum\EmailTemplate::PAP
            provider: !php/const App\Enum\Provider::PAP
            name: "\"PAP.fr\""
            email: users-alertes@pap.fr
        -
            id: !php/const App\Enum\EmailTemplate::SELOGER
            provider: !php/const App\Enum\Provider::SELOGER
            name: SeLoger
            email: seloger@al.alerteimmo.com

services:
    App\Service\EmailTemplateManager:
        autowire: true
        autoconfigure: true
        arguments:
            $emailTemplates: '%email_templates%'
