services:
    Google_Client:
        class: Google_Client
        calls:
            - [setDeveloperKey, ['%env(GOOGLE_API_KEY)%']]
            - [setClientId, ['%env(OAUTH_GOOGLE_ID)%']]
            - [setClientSecret, ['%env(OAUTH_GOOGLE_SECRET)%']]

    Google_Service_Gmail:
        class: Google_Service_Gmail
        arguments:
            - '@Google_Client'
