!php/const App\Definition\SiteEnum::LEBONCOIN:
    !php/const App\Definition\CityEnum::NANTES: Nantes
    !php/const App\Definition\CityEnum::RENNES: Rennes
!php/const App\Definition\SiteEnum::LOGIC_IMMO:
    !php/const App\Definition\CityEnum::NANTES: nantes,240
    !php/const App\Definition\CityEnum::RENNES: rennes,294
!php/const App\Definition\SiteEnum::OUESTFRANCE_IMMO:
    !php/const App\Definition\CityEnum::NANTES: nantes-44-44000
    !php/const App\Definition\CityEnum::RENNES: rennes-35-35000
!php/const App\Definition\SiteEnum::SELOGER:
    !php/const App\Definition\CityEnum::NANTES: 440109
    !php/const App\Definition\CityEnum::RENNES: 350238
